"""
Smart Store Operations — Pydantic Schemas for CV Inference API
Phase 4: Computer Vision Pipeline (Shelf AI)
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum
from datetime import datetime


# ─── Enums ───────────────────────────────────────────────────────────────────

class FacingStatus(str, Enum):
    PRODUCT_PRESENT = "product_present"
    EMPTY_FACING = "empty_facing"
    WRONG_PRODUCT = "wrong_product"
    PARTIAL_FACING = "partial_facing"


class AlertPriority(str, Enum):
    URGENT = "urgent"
    NORMAL = "normal"
    LOW = "low"


# ─── Detection Schemas ───────────────────────────────────────────────────────

class BoundingBox(BaseModel):
    """Bounding box coordinates (normalized 0-1)"""
    x_min: float = Field(..., ge=0, le=1, description="Left edge normalized")
    y_min: float = Field(..., ge=0, le=1, description="Top edge normalized")
    x_max: float = Field(..., ge=0, le=1, description="Right edge normalized")
    y_max: float = Field(..., ge=0, le=1, description="Bottom edge normalized")


class Detection(BaseModel):
    """Single object detection result"""
    class_name: FacingStatus
    confidence: float = Field(..., ge=0, le=1)
    bbox: BoundingBox
    product_id: Optional[str] = None
    aisle: Optional[str] = None
    bay: Optional[int] = None
    shelf_level: Optional[int] = None


class DetectionRequest(BaseModel):
    """Input for /detect endpoint"""
    image_base64: str = Field(..., description="Base64-encoded JPEG/PNG image")
    store_id: str = Field(..., description="Store identifier")
    camera_id: str = Field(..., description="Camera identifier")
    aisle: Optional[str] = Field(None, description="Aisle identifier if known")
    bay: Optional[int] = Field(None, description="Bay number if known")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class DetectionResponse(BaseModel):
    """Output from /detect endpoint"""
    request_id: str
    store_id: str
    camera_id: str
    timestamp: datetime
    inference_time_ms: float
    detections: List[Detection]
    total_facings: int
    empty_facings: int
    stockout_rate: float = Field(..., ge=0, le=1)
    model_version: str


# ─── Planogram Schemas ────────────────────────────────────────────────────────

class FacingDeviation(BaseModel):
    """Per-facing deviation from golden planogram"""
    position: int = Field(..., description="Facing position index (left to right)")
    shelf_level: int
    expected_product_id: str
    detected_product_id: Optional[str]
    status: FacingStatus
    similarity_score: float = Field(..., ge=0, le=1)


class PlanogramRequest(BaseModel):
    """Input for /planogram endpoint"""
    image_base64: str = Field(..., description="Base64-encoded shelf image")
    store_id: str
    aisle: str
    bay: int
    planogram_id: str = Field(..., description="Reference planogram identifier")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PlanogramResponse(BaseModel):
    """Output from /planogram endpoint"""
    request_id: str
    store_id: str
    aisle: str
    bay: int
    planogram_id: str
    timestamp: datetime
    inference_time_ms: float
    compliance_score: float = Field(..., ge=0, le=1,
                                     description="Overall planogram compliance 0-1")
    total_facings: int
    compliant_facings: int
    deviations: List[FacingDeviation]
    model_version: str


# ─── Alert Schemas ────────────────────────────────────────────────────────────

class ShelfOOSAlert(BaseModel):
    """MQTT alert payload for out-of-stock detection
    Published to: stores/{store_id}/shelf/oos
    """
    alert_id: str
    store_id: str
    aisle: str
    bay: int
    shelf_level: int
    product_id: str
    confidence: float = Field(..., ge=0, le=1)
    consecutive_frames: int = Field(..., ge=3)
    timestamp: datetime
    image_url: str
    priority: AlertPriority = AlertPriority.NORMAL
    camera_id: str


# ─── Sensor Fusion Schemas ────────────────────────────────────────────────────

class ShelfState(BaseModel):
    """Unified shelf state after sensor fusion (Phase 5)"""
    store_id: str
    aisle: str
    bay: int
    shelf_level: int
    product_id: str
    sku_code: str
    camera_status: Optional[FacingStatus] = None
    camera_confidence: Optional[float] = None
    weight_grams: Optional[float] = None
    weight_expected_grams: Optional[float] = None
    rfid_present: Optional[bool] = None
    rfid_tag_count: Optional[int] = None
    fused_confidence: float = Field(..., ge=0, le=1)
    is_out_of_stock: bool
    predicted_stockout_time_min: Optional[float] = None
    timestamp: datetime
    window_start: datetime
    window_end: datetime


class RestockTask(BaseModel):
    """Restock task generated by replenishment engine"""
    task_id: str
    store_id: str
    aisle: str
    bay: int
    shelf_level: int
    product_id: str
    sku_code: str
    product_name: str
    current_quantity_estimate: int
    restock_quantity: int
    priority: AlertPriority
    fused_confidence: float
    predicted_stockout_time_min: Optional[float]
    assigned_to: Optional[str] = None
    created_at: datetime
    due_by: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    completion_photo_url: Optional[str] = None


# ─── Queue Schemas ────────────────────────────────────────────────────────────

class QueueStatus(BaseModel):
    """Real-time queue status per lane"""
    store_id: str
    lane_id: int
    queue_length: int
    estimated_wait_seconds: float
    is_open: bool
    cashier_id: Optional[str] = None
    lane_type: str = Field(..., description="manned or self_checkout")
    timestamp: datetime


class QueueAlert(BaseModel):
    """Queue management alert"""
    alert_id: str
    store_id: str
    alert_type: str = Field(..., description="warn_threshold or open_threshold")
    lane_id: int
    queue_length: int
    estimated_wait_seconds: float
    recommended_action: str
    assigned_cashier_id: Optional[str] = None
    timestamp: datetime


# ─── LP Schemas ───────────────────────────────────────────────────────────────

class BehaviourClass(str, Enum):
    NORMAL_BROWSING = "normal_browsing"
    PROLONGED_LOITERING = "prolonged_loitering"
    CONCEALMENT_GESTURE = "concealment_gesture"
    TICKET_SWITCHING = "ticket_switching"
    NORMAL_CHECKOUT = "normal_checkout"


class LPAlert(BaseModel):
    """Loss prevention alert"""
    alert_id: str
    store_id: str
    zone: str
    behaviour_detected: BehaviourClass
    confidence: float = Field(..., ge=0, le=1)
    customer_tracking_id: str
    dwell_time_seconds: Optional[float] = None
    video_clip_url: Optional[str] = None
    rfid_discrepancy: Optional[bool] = None
    timestamp: datetime
    acknowledged: bool = False
    officer_id: Optional[str] = None


# ─── API Response Wrappers ────────────────────────────────────────────────────

class HealthResponse(BaseModel):
    status: str = "healthy"
    version: str
    model_version: str
    uptime_seconds: float
    inference_count: int
    avg_inference_ms: float


class ErrorResponse(BaseModel):
    error: str
    detail: str
    request_id: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
